(function(g){var window=this;var xya=function(a,b,c,d){var e=b.kc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Zb(c,d?d:"mqdefault.jpg");var k=b instanceof g.kQ?g.uX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.kS(f).type;var m=b instanceof g.kQ?b.za:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Mn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.mS&&(c.playlist_length=b.getLength());a.update(c)},h7=function(a,b){g.tX.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},i7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",T:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",T:c,K:[{H:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",T:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",T:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",T:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.ra["ytp-upnext-cancel"];b=this.ra["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.L(this,this.B);this.B.V("click",this.fB,this);this.B.Aa(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],T:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.L(this,c);c.V("click",this.fB,this);c.Aa(b);this.o=
a;this.J=this.ra["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Ft(this.an,5E3,this);g.L(this,this.G);this.I=0;this.P(this.ra["ytp-upnext-autoplay-icon"],"click",this.bR);this.cB();this.P(a,"autonavvisibility",this.cB);this.P(a,"mdxnowautoplaying",this.qQ);this.P(a,"mdxautoplaycanceled",this.rQ);this.P(a,"mdxautoplayupnext",this.qD);3==this.o.Ua()&&(a=(a=g.sW(g.nW(this.o)))?a.wI():null)&&this.qD(a)},yya=function(a,b){a.C=b;
xya(a,b,g.X(a.o),"hqdefault.jpg")},j7=function(a,b){a.A||(g.IG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.VG)(),a.A=new g.Ft((0,g.z)(a.lq,a,b),25),a.lq(b));
g.Sp(a.element,"ytp-upnext-autoplay-paused")},l7=function(a){k7(a);
a.I=(0,g.VG)();a.lq();g.S(a.element,"ytp-upnext-autoplay-paused")},k7=function(a){a.A&&(a.A.dispose(),a.A=null)},zya=function(a){h7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",T:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.L(this,this.A);this.A.Aa(this.element);this.B=new g.g1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Wl,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.B);this.B.Aa(this.A.ra["html5-subscribe-button-container"]);this.hide()},
m7=function(a){var b=g.X(a);
b=b.A&&!b.F;g.Y.call(this,{H:"a",M:"ytp-videowall-still",T:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",T:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",T:g.pF||g.gf?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.V("click",this.C);this.V("keypress",this.D);if(g.X(a).da){a=a.app.ba;b=this.element;g.lb(a.g,b);g.qb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.bf(this,(0,g.z)(a.F,a,b))}},n7=function(a){h7.call(this,a,"videowall-endscreen");
this.ba=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.U=!1;this.F=new g.qG(this);g.L(this,this.F);this.L=new g.Ft(g.Ga(g.S,this.element,"ytp-show-tiles"),0);g.L(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.rE()]});g.L(this,b);b.Aa(this.element);b.V("click",this.OM,this);this.O=new g.WW({H:"div",M:"ytp-endscreen-content"});g.L(this,this.O);this.O.Aa(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
T:{"aria-label":g.U("YTP_NEXT")},K:[g.sE()]});g.L(this,b);b.Aa(this.element);b.V("click",this.NM,this);this.A=new i7(a);g.L(this,this.A);g.OW(this.o,this.A.element,4);this.hide()},o7=function(a){return g.PW(a.o)&&a.pq()&&!a.I},Aya=function(a){return(0,g.I)(a.jg,function(a){return g.i_(a)})},p7=function(a){var b=a.Rs();
b!=a.U&&(a.U=b,a.o.W("autonavvisibility"))},q7=function(a){g.pX.call(this,a);
g.mE({});this.o=null;this.isAvailable=!0;this.A=new g.qG(this);g.L(this,this.A);this.B=g.X(a);Bya(a)?this.o=new n7(this.g):this.B.Ba?this.o=new zya(this.g):this.o=new h7(this.g);g.L(this,this.o);g.OW(this.g,this.o.element,4);this.nC();this.A.P(a,"videodatachange",this.nC,this);this.A.P(a,"crn_endscreen",this.pM,this);this.A.P(a,"crx_endscreen",this.qM,this)},Bya=function(a){a=g.X(a);
return a.re&&!a.Ba};g.p(h7,g.tX);h7.prototype.create=function(){this.N=!0};
h7.prototype.destroy=function(){this.N=!1};
h7.prototype.pq=function(){return!1};
h7.prototype.Rs=function(){return!1};g.p(i7,g.Y);g.h=i7.prototype;g.h.an=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.cB=function(){this.o.app.fa||g.bX(this,g.oW(this.o))};
g.h.RQ=function(){window.focus();this.an()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.lq=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.VG)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Ua()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.BW(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.kc(),this.an(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Zb(b)}),this.F=this.P(this.D,"click",this.RQ),this.G.start())}k7(this);
this.o.Ej(!1,a)};
g.h.bR=function(a){!g.Td(this.B.element,g.gG(a))&&g.XZ(a,this.o)&&this.select()};
g.h.fB=function(){g.CW(this.o,"autonavcancel");g.qW(this.o,!0)};
g.h.qQ=function(a){this.o.Ua();this.show();j7(this,a)};
g.h.qD=function(a){this.o.Ua();this.C&&this.C.kc().videoId==a.kc().videoId||yya(this,a)};
g.h.rQ=function(){this.o.Ua();k7(this);this.hide()};
g.h.X=function(){k7(this);this.an();g.Y.prototype.X.call(this)};g.p(zya,h7);g.p(m7,g.Y);m7.prototype.Uj=function(){var a=this.A.kc().videoId,b=this.A.getPlaylistId();g.S1(this.o.app,a,this.A.Xd,b,void 0,void 0)};
m7.prototype.C=function(a){g.SW(this.o,this.element);g.XZ(a,this.o,this.B,this.A.Xd||void 0)&&this.Uj()};
m7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.lG(a)||(this.Uj(),g.nG(a))}};g.p(n7,h7);g.h=n7.prototype;g.h.create=function(){h7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=Aya(a),this.D=a);this.yh();this.F.P(this.o,"appresize",this.yh);this.F.P(this.o,"videodatachange",this.PM);this.F.P(this.o,"autonavchange",this.fA);this.F.P(this.o,"autonavcancel",this.MM);this.F.P(this.element,"transitionend",this.iS)};
g.h.destroy=function(){g.sG(this.F);g.df(this.B);this.B=[];this.C=null;h7.prototype.destroy.call(this);g.Sp(this.element,"ytp-show-tiles");this.L.stop()};
g.h.pq=function(){return 1!=this.D.autonavState};
g.h.show=function(){h7.prototype.show.call(this);g.Sp(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.Gt(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.qW(this.o,!1);var a=o7(this);g.PW(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.BW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.pq()?"enabled":"disabled"});a?(p7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.wh()?this.A.select(!0):j7(this.A):3==this.D.autonavState&&
l7(this.A)):(g.qW(this.o,!0),p7(this))};
g.h.hide=function(){h7.prototype.hide.call(this);l7(this.A);p7(this)};
g.h.iS=function(a){g.gG(a)==this.element&&this.yh()};
g.h.yh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Ih(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(d<f||e<k);){var q=d/2,r=e/2,v=d<=f-2&&n>=r*m,A=e<=k-2&&n>=q*m;if((q+1)/r*c/b>b/(q/(r+1)*c)&&A)n-=q*m,e+=2;else if(v)n-=r*m,d+=2;else if(A)n-=q*m,e+=2;else break}c=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=d)&&(c=!0);m=96*
d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.bd(a.width/m||1,1,1.21);n*=g.bd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Hh(a,m,n);g.ph(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});yya(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",o7(this));p7(this);m+=4;n+=4;for(f=b=0;f<d;f++)for(k=0;k<e;k++)if(q=b,r=0,c&&f>=d-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.cd(q+this.G,l),0!=
r){v=this.B[b];v||(v=new m7(this.o),this.B[b]=v,a.appendChild(v.element));A=Math.floor(n*k/e);var C=Math.floor(m*f/d),E=Math.floor(n*(k+r)/e)-A-4,Q=Math.floor(m*(f+r)/d)-C-4;g.wh(v.element,C,A);g.Hh(v.element,Q,E);g.ph(v.element,"transitionDelay",(k+f)/20+"s");g.T(v.element,"ytp-videowall-still-mini",1==r);g.T(v.element,"ytp-videowall-still-large",2<r);r=v;q=this.C[q];r.A=q;xya(r,q,g.X(r.o),g.Qp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");v=q.Xd;q=r.o;g.X(q).da&&(q=q.app.ba,
r=r.element,v=v&&v.itct,A=r.getAttribute("data-visual-id"),g.lb(q.g,r),g.QW(q,"onLogServerVeCreated",{id:A,tracking_params:v}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Ld(e.element),g.cf(e);this.B.length=b}};
g.h.PM=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=Aya(a),this.D=a,this.yh())};
g.h.NM=function(){this.G+=this.B.length;this.yh()};
g.h.OM=function(){this.G-=this.B.length;this.yh()};
g.h.DK=function(){return!!this.A.A};
g.h.fA=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,k7(this.A),this.g&&this.yh()):(this.J=!0,this.g&&o7(this)&&(2==a?j7(this.A):3==a&&l7(this.A)))};
g.h.MM=function(a){if(a){for(a=0;a<this.B.length;a++)g.TW(this.ba,this.B[a].element,!0);this.fA(1)}else this.I=null,this.J=!1;this.yh()};
g.h.Rs=function(){return this.g&&o7(this)};g.p(q7,g.pX);g.h=q7.prototype;g.h.bA=function(){var a=this.g.ga(),b=!Bya(this.g)||!(!a.jg||!a.jg.length);a=g.DQ(a,"ypc_module");var c=g.T1(this.g.app);return(b||!1)&&!a&&!c};
g.h.aA=function(){return this.o.Rs()};
g.h.AK=function(){return this.aA()?this.o.DK():!1};
g.h.X=function(){g.KW(this.g,"endscreen");g.pX.prototype.X.call(this)};
g.h.load=function(){g.pX.prototype.load.call(this);this.o.show();g.X(this.g).Ba&&.01>Math.random()&&g.BW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.pX.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.pM=function(a){this.bA()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.qM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.nC=function(){g.KW(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0);a=new g.gS(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.gS(0x8000000000000,0x8000000000000,{id:"load",priority:g.eS.qF,namespace:"endscreen"});g.HW(this.g,[a,b])};g.KZ.endscreen=q7;})(_yt_player);
